services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: uadmin
      POSTGRES_PASSWORD: padmin
      POSTGRES_DB: walnut
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    depends_on:
      - postgres
    environment:
      DB_USER: uadmin
      DB_PASSWORD: padmin
      DB_HOST: postgres
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  pg_data:
